/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sollyu_xposed_hook_model_worker_HookModelAppListWorker */

#ifndef _Included_com_sollyu_xposed_hook_model_worker_HookModelAppListWorker
#define _Included_com_sollyu_xposed_hook_model_worker_HookModelAppListWorker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sollyu_xposed_hook_model_worker_HookModelAppListWorker
 * Method:    GetString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sollyu_xposed_hook_model_worker_HookModelAppListWorker_GetString
  (JNIEnv *, jobject, jint)
  {
  return (*env)->NewStringUTF(env,"Hello From JNI!");
  }

#ifdef __cplusplus
}
#endif
#endif
