/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sollyu_xposed_hook_model_worker_HookModelAppListWorker */

#ifndef _Included_com_sollyu_xposed_hook_model_worker_HookModelAppListWorker
#define _Included_com_sollyu_xposed_hook_model_worker_HookModelAppListWorker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sollyu_xposed_hook_model_worker_HookModelAppListWorker
 * Method:    GetAppListString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sollyu_xposed_hook_model_worker_HookModelAppListWorker_GetAppListString
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sollyu_xposed_hook_model_worker_HookModelAppListWorker
 * Method:    GetAppSettingsString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sollyu_xposed_hook_model_worker_HookModelAppListWorker_GetAppSettingsString
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sollyu_xposed_hook_model_worker_HookModelAppListWorker
 * Method:    GetAppSettingString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sollyu_xposed_hook_model_worker_HookModelAppListWorker_GetAppSettingString
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_sollyu_xposed_hook_model_worker_HookModelAppListWorker
 * Method:    onCreate
 * Signature: (Landroid/content/Context;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sollyu_xposed_hook_model_worker_HookModelAppListWorker_onCreate
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
